### ISSUE TITLE
What's the function for --enable-audio-playback?

### ISSUE THREAD

**Issue by yan-2** [TeamFightingICE/FightingICE#53]
Hi, I don't really understand the function of "--enable-audio-playback" flag. After adding it, I just heard echos from the gameplay.
Could you please explain it a little more, and when should I use it for sound design?

**Comment by Staciiaz** [comment]
Sorry for the late reply. Generally, you don't need to enable that option; it's primarily for testing purposes to see how the audio data sent to the game system appears. Alternatively, you can enable it if your sound design didn't generate the expected output audio.
